FROM ubuntu:latest

ENV container=docker

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      python3 \
      systemd \
      systemd-sysv \
      dbus \
      sudo \
      ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
