---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 192.168.10.29
          ansible_user: kudryashov

    vector:
      hosts:
        vector-01:
          ansible_host: 192.168.10.29
          ansible_user: kudryashov
