---
lighthouse_name: lighthouse
lighthouse_root: /var/www/lighthouse
lighthouse_index_url: https://raw.githubusercontVKCOM/lighthouseent.com/VKCOM/lighthouse/master/index.html
lighthouse_index_path: "{{ lighthouse_root }}/index.html"

lighthouse_nginx_config_path: /etc/nginx/sites-available/default
lighthouse_listen_port: 80
